### PR TITLE
Extending the current pr

### PR DESCRIPTION
**Pull request by bsipocz**
@astrofrog I'll ping you whenever this is ready to be merged
- Fixing ci-helper filename
- putting back non-confirmation thus builds don't halt into waiting

### CODE REVIEW

**Comment by astrofrog** [comment]
For the ``--yes`` stuff I was actually thinking we should add the config option to ``ci-helpers`` to make it so that ``--yes`` is included by default. I thought I added it, but apparently not. Could you add this and remove ``--yes`` again here?

**Comment by astrofrog** [comment]
This is done with

```
conda config --set always_yes true
```

**Comment by astrofrog** [comment]
Ah you have it here:

https://github.com/astropy/ci-helpers/blob/master/travis/setup_dependencies_common.sh#L4

Why do you need to add it back in this PR?

**Comment by astrofrog** [comment]
@bsipocz - thanks for working on all this btw! :smile:

**Comment by bsipocz** [comment]
@astrofrog - I put back the ``--yes`` as the builds halted in a [y/n] wait for one of the tests runs, but now looking back it was before I added back the setup_dependencies_common script. 

Anyway, I'll try to make things work in ``ci-helpers`` with photutils first and then make the relevant changes to the template.

**Comment by astrofrog** [comment]
@bsipocz - thanks! Just as a heads-up, I'm planning on actually adding a .travis.yml file and appveyor.yml file in ci-helpers so it can test itself, but that shouldn't interfere with what you are doing (but will make it easier in future to test changes)

**Comment by astrofrog** [comment]
I'll just go ahead and merge this since Travis will have to run in the main PR anyway.

**Pull request merged**
